### PR TITLE
Add percision parameter to fileSize

### PR DESCRIPTION
**Pull request by nathancahill**
Sometimes 3 MB is more humane than 3.12 MB. This allows specifying the precision as a parameter of fileSize() instead of having it hardcoded as 2:

```
Humanize.fileSize(1024 * 2000, 0)
// "1 Mb"
```

### CODE REVIEW

**Comment by aaylward** [comment]
thanks @nathancahill That seems legit to me. Mind adding a test for it?

@b-ash do we still support node 0.8?

**Comment by b-ash** [comment]
0.8 is pretty old, so I'd be okay with bailing on it.

**Comment by hijonathan** [comment]
[https://www.youtube.com/watch?v=1IOukA10QeQ](https://www.youtube.com/watch?v=1IOukA10QeQ)

**Comment by nathancahill** [comment]
Bump, added a test for file precision.

**Comment by geekjuice** [comment]
@nathancahill Sorry for the delayed responses :disappointed: Mind rebasing/re-applying these changes to the [new source](https://github.com/HubSpot/humanize/blob/master/src/humanize.js#L140-L154)? I'll be sure to merge it in right away :+1:

**Comment by nathancahill** [comment]
Thanks @geekjuice! Submitted #70.

**Pull request closed without merging**
