### PR TITLE
fix #67

### LINKED ISSUE #67: Uncaught TypeError: Cannot set property 'Humanize' of undefined
Exception is thrown when the package is minified.

### PR DESCRIPTION
**Pull request by tusharmath**

### CODE REVIEW

**Comment by geekjuice** [comment]
:+1:

**Comment by tusharmath** [comment]
Is this released?

**Comment by geekjuice** [comment]
Adding the changes to the actual source (not compiled JS) and few more things before releasing

**Comment by tusharmath** [comment]
Sure. Take a look at Semantic Release https://github.com/semantic-release/semantic-release
Its pretty awesome, if you want to automate your release process.

**Comment by geekjuice** [comment]
Published as `1.6.0`

**Pull request merged**
